// Kuzu Knowledge Graph – RedNode
CREATE NODE TABLE Project(name STRING, path STRING, PRIMARY KEY(name));
CREATE NODE TABLE Technology(name STRING, PRIMARY KEY(name));
CREATE NODE TABLE Repo(url STRING, PRIMARY KEY(url));
CREATE NODE TABLE File(path STRING, PRIMARY KEY(path));
CREATE NODE TABLE Function(name STRING, file STRING, line INT64, PRIMARY KEY(name, file));
CREATE REL TABLE USES(FROM Project TO Technology);
CREATE REL TABLE CONTAINS(FROM Repo TO File);
CREATE REL TABLE DEFINES(FROM File TO Function);
